### ISSUE TITLE
scroll to current time

### ISSUE THREAD

**Issue by kohdesmond** [lyahdav/LIYDateTimePicker#2]
Hi thanks for this awesome library!

just wondering if there is a way to scroll to current time

**Comment by lyahdav** [comment]
Also if you want to start the calendar showing the current time, just make sure to pass in the current time to the convenience constructor:
```
[LIYDateTimePickerViewController timePickerForDate:[NSDate date] delegate:self]
```

**Comment by lyahdav** [comment]
Fixed in https://github.com/lyahdav/LIYDateTimePicker/commit/64cf66ea30a85396391c00db9505203874779f60. Now you can call `[dayTimePicker scrollToTime:[NSDate date]]`
