### ISSUE TITLE
middle time indicator position not correct when I rotate the simulator from portrait to landscape and then back to portait.

### ISSUE THREAD

**Issue by chakming** [lyahdav/LIYDateTimePicker#4]
Tested in iPhone 5 iOS 8.1 simulator.

![screen shot 2015-01-12 at 2 56 00 pm](https://cloud.githubusercontent.com/assets/138537/5699788/2666439e-9a6b-11e4-8783-28264240957a.png)

**Comment by lyahdav** [comment]
I'll try to look into this within a few days. Thanks for the clear bug report. I've worked around this by disabling rotation up until now, obviously not ideal.

**Comment by lyahdav** [comment]
Fixed in https://github.com/lyahdav/LIYDateTimePicker/commit/64cf66ea30a85396391c00db9505203874779f60.
