### ISSUE TITLE
MZDayPicker

### ISSUE THREAD

**Issue by finddoc** [lyahdav/LIYDateTimePicker#5]
Hi

I found the dependency of MZDayPicker couldn't be pulled. It shows 404 error.
pod 'MZDayPicker', :git => 'https://github.com/joefrank99/MZDayPicker.git"

Thanks.
Regards
Alex

**Comment by lyahdav** [comment]
Oops. I will have to fix that soon. In the mean time change it to point to
https://github.com/handl/MZDayPicker and you should be good.

**Comment by finddoc** [comment]
Thanks, but with this fork, it don't have daySelectedFont property and compile error occur.
    self.dayPicker.daySelectedFont = self.defaultSelectedFontFamilyName;

**Comment by lyahdav** [comment]
Sorry, it should be the highlight_today branch on that fork. You can
specify that in the Podfile.
https://github.com/handl/MZDayPicker/tree/hightlight_today?files=1
I'll update the readme in the future, on my phone now.
